name: L

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  curl_request:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request
        run: curl -s -o /dev/null -w "%{http_code}" "https://nekocurit.asia/"
